apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: replicas.yaml
- path: env.yaml

  target:
    kind: ConfigMap
    name: backend-env
- path: secret.yaml

  target:
    kind: Secret
    name: db-secret
